version: '3.5'

services:
    php:
        image: nemrtvej/sorted-linked-list
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            args:
                PUID: ${PUID}
                PGID: ${PGID}
        volumes:
            - ./:/app/
        user: www-data
        environment:
            PGID: ${PUID}
            PUID: ${PUID}
