name: Code Quality
run-name: Run code quality jobs
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Build image
              run: |
                export PGID=$(id -g)
                export PUID=$(id -u)
                docker compose build php
            - name: Store image locally
              run: docker save nemrtvej/sorted-linked-list -o storage/php.tar
            - name: start the container & load dependencies
              run: |
                export PGID=$(id -g)
                export PUID=$(id -u)
                make start composer-install
                tar czvf storage/vendors.tar.gz vendor/*
            - name: Upload image artifact
              uses: actions/upload-artifact@v3
              with:
                name: docker-image
                path: storage/php.tar
                retention-days: 1
            - name: Upload vendors
              uses: actions/upload-artifact@v3
              with:
                name: vendors
                path: storage/vendors.tar.gz
                retention-days: 1

    phpstan:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Download the docker image
              uses: actions/download-artifact@v3
              with:
                name: docker-image
                path: storage/php.tar
            - name: Download the vendors
              uses: actions/download-artifact@v3
              with:
                name: vendors
                path: storage/vendors.tar.gz
            - name: load the docker image and vendors
              run: |
                ls -lah
                ls -lah storage/
                docker load -i storage/php.tar
            - name: start the container
              run: |
                export PGID=$(id -g)
                export PUID=$(id -u)
                make start
                mkdir vendor
                tar xzvf storage/vendors.tar.gz vendor/*
            - name: run phpstan
              run: make stan

#    cs:
#        runs-on: ubuntu-latest
#        needs: build
#        steps:
#            - name: Check out repository code
#              uses: actions/checkout@v3
#            - name: Download the built artifact
#              uses: actions/download-artifact@v3
#              with:
#                name: docker-image
#            - name: load the docker image
#              run: docker load -i storage/php.tar
#            - name: run cs
#              run: make composer-install cs
#
#    test:
#        runs-on: ubuntu-latest
#        needs: build
#        steps:
#            - name: Check out repository code
#              uses: actions/checkout@v3
#            - name: Download the built artifact
#              uses: actions/download-artifact@v3
#              with:
#                name: docker-image
#            - name: load the docker image
#              run: docker load -i storage/php.tar
#            - name: run test
#              run: make composer-install test
#
#    security-advisories:
#        runs-on: ubuntu-latest
#        needs: build
#        steps:
#            - name: Check out repository code
#              uses: actions/checkout@v3
#            - name: Download the built artifact
#              uses: actions/download-artifact@v3
#              with:
#                name: docker-image
#            - name: load the docker image
#              run: docker load -i storage/php.tar
#            - name: run security advisories
#              run: make composer-install security
